<footer>
		<div class="site-footer">
			<section>
				<h5>About</h5>
				<p class="aboutus">
					We are a group of 5 students studying in Swinburne university of technology who are making<br>
					this website for our assigned company called JavaStorm. JavaStorm focuses on providing the <br>
					most efficient code or snippets as the code wants to be simple.<i> Simple yet unique.</i> <br>
					We help our customers build up concepts in different programming languages that include<br>
					C, C++, HTML, CSS, Bootstrap, but mainly, Java.
				</p>
			</section>
			<section>
				<h5>Contact us</h5>
				<ul class="Contact us">
					<li>+61 401 508 993</li>
					<li>+61 401 508 982</li>
					<li><a href="mailto:javastorm@gmail.com" class="link">javaStorm@gmail.com</a></li>
					<li>Swinburne University, Hawthorn, VIC.</li>
				</ul>
			</section>
			<section>
				<h5>Quick Links</h5>
				<ul class="footer-links">
					<li><a href="about.php">About Us</a></li>
					<li><a href="apply.php">Apply</a></li>
					<li><a href="jobs.php">Jobs</a></li>
					<li>
						<a
							href="https://www.google.com/maps/place/Swinburne+University+of+Technology/@-37.8221504,145.0367659,17z/data=!3m1!4b1!4m6!3m5!1s0x6ad642326bae5aaf:0x75e96bbd4988f769!8m2!3d-37.8221504!4d145.0389546!16zL20vMDFrcV9z">
							Find Us
						</a>
					</li>
					<li><a href="https://youtu.be/Cwu3FOV8aXw">Youtube Demonstration Video</a></li>
				</ul>
			</section>
		</div>

		<br>
		<p class="copyright-text"> Copyright &copy; 2017 All Rights Reserved by JavaStorm
		</p>

	</footer>