table {
  border-collapse: collapse;
  border-radius: 10px;
  /* border for table with border collapse */
  border-style: hidden;
  box-shadow: 0 0 0 1px var(--accent-darker);
  overflow: hidden;
}

table,
th,
td {
  padding: 8px;
  text-align: center;
  border: 1px solid var(--accent-darker);
}

th {
  color: white;
  background-color: var(--accent);
}

.time {
  font-weight: bold;
}

/* vim: ft=css */
