h2,
h3,
h4,
h5 {
  font-family: var(--font-heading);
  /* space after headers */
  margin: 1.5rem 0;
}

h1 {
  /* the requirement askes me to have short-hand font for h1 */
  font: bold 4em var(--font-heading);
  letter-spacing: 0.5px;
  margin: 1rem 0;
}

h2 {
  letter-spacing: 0px;
  font-size: 3em;
}

h3 {
  letter-spacing: 0.25px;
  font-size: 2em;
}

h4 {
  letter-spacing: 0.5px;
  font-size: 1.75em;
}

h5 {
  letter-spacing: 1px;
  font-size: 1.3em;
}

input,
textarea,
span,
label,
p {
  font: 1em var(--font-sans);
  /* easier to read with bigger line height */
  line-height: 1.3;
}

p {
  /* space between paragraph */
  margin-bottom: 1.5em;
}

/* vim: ft=css */
